[workspace]
members = ["bevy_eventlistener_derive"]
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "bevy_eventlistener"
version = "0.1.0"
edition = "2021"
description = "Event listeners and callbacks for bevy"
license = "MIT OR Apache-2.0"
repository = "https://github.com/aevyrie/bevy_eventlistener"
keywords = ["gamedev", "bevy", "eventlistener", "callbacks"]
categories = ["game-engines", "rendering"]

[dependencies]
bevy = { version = "0.10", default-features = false }

[dev-dependencies]
bevy_eventlistener_derive = { path = "bevy_eventlistener_derive", version = "0.1" }
rand = "0.8"
criterion = "0.5"
